AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: AI Chef Complete Backend Infrastructure

Globals:
  Function:
    Runtime: python3.11
    Timeout: 30
    MemorySize: 256
    Environment:
      Variables:
        SESSIONS_TABLE_NAME: !Ref SessionsTable
        RESULTS_TABLE_NAME: !Ref ResultsTable
  Api:
    Cors:
      AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
      AllowOrigin: "'*'"

Resources:
  # DynamoDB Tables
  SessionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ai-chef-sessions
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: sessionId
          AttributeType: S
      KeySchema:
        - AttributeName: sessionId
          KeyType: HASH
      TimeToLiveSpecification:
        AttributeName: TTL
        Enabled: true

  ResultsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ai-chef-results
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: sessionId
          AttributeType: S
      KeySchema:
        - AttributeName: sessionId
          KeyType: HASH

  NutritionTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ai-chef-nutrition
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: ingredient
          AttributeType: S
      KeySchema:
        - AttributeName: ingredient
          KeyType: HASH

  # API Gateway
  AiChefApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: ai-chef-api
      StageName: prod

  # Lambda Functions
  SessionCreateFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ai-chef-session-create
      CodeUri: backend/lambda/session-create/
      Handler: index.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SessionsTable
      Events:
        CreateSession:
          Type: Api
          Properties:
            RestApiId: !Ref AiChefApi
            Path: /sessions
            Method: post

  SessionUpdateFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ai-chef-session-update
      CodeUri: backend/lambda/session-update-profile/
      Handler: index.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SessionsTable
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
              Resource: '*'
      Events:
        UpdateSession:
          Type: Api
          Properties:
            RestApiId: !Ref AiChefApi
            Path: /sessions/update
            Method: post

  SessionStatusFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ai-chef-session-status
      CodeUri: backend/lambda/session-status/
      Handler: index.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SessionsTable
      Events:
        GetStatus:
          Type: Api
          Properties:
            RestApiId: !Ref AiChefApi
            Path: /sessions/{sessionId}/status
            Method: get

  RecipeFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ai-chef-recipe
      CodeUri: backend/lambda/recipe/
      Handler: index.handler
      Timeout: 300
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SessionsTable
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
              Resource: '*'

  RecipeWithRagFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ai-chef-create-recipe-with-rag
      CodeUri: backend/lambda/create-recipe-with-rag/
      Handler: index.handler
      Timeout: 300
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SessionsTable
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
              Resource: '*'

  PriceFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ai-chef-price
      CodeUri: backend/lambda/price/
      Handler: index.handler
      Timeout: 60
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SessionsTable
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: '*'

  NutritionCalculatorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ai-chef-nutrition-calculator
      CodeUri: backend/lambda/nutrition-calculator/
      Handler: index.handler
      Timeout: 60
      Environment:
        Variables:
          NUTRITION_TABLE_NAME: !Ref NutritionTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SessionsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref NutritionTable

  NutritionLookupFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ai-chef-recipe-nutrition-lookup
      CodeUri: backend/lambda/recipe-nutrition-lookup/
      Handler: index.handler
      Environment:
        Variables:
          NUTRITION_TABLE_NAME: !Ref NutritionTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref NutritionTable

  NutritionInitializerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ai-chef-nutrition-data-initializer
      CodeUri: backend/lambda/nutrition-data-initializer/
      Handler: index.handler
      Timeout: 300
      Environment:
        Variables:
          NUTRITION_TABLE_NAME: !Ref NutritionTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref NutritionTable

  RecipeImageGeneratorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ai-chef-recipe-image-generator
      CodeUri: backend/lambda/recipe-image-generator/
      Handler: index.handler
      Timeout: 60
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SessionsTable
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
              Resource: '*'

  ProcessFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ai-chef-process
      CodeUri: backend/lambda/process/
      Handler: index.handler
      Timeout: 300
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SessionsTable
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - states:StartExecution
              Resource: !Ref AiChefWorkflow
      Events:
        ProcessSession:
          Type: Api
          Properties:
            RestApiId: !Ref AiChefApi
            Path: /sessions/{sessionId}/process
            Method: post

  CombineFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ai-chef-combine
      CodeUri: backend/lambda/combine/
      Handler: index.handler
      Timeout: 60
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SessionsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref ResultsTable

  ResultFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ai-chef-result
      CodeUri: backend/lambda/result/
      Handler: index.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ResultsTable
      Events:
        GetResult:
          Type: Api
          Properties:
            RestApiId: !Ref AiChefApi
            Path: /results/{sessionId}
            Method: get

  # Step Functions
  AiChefWorkflow:
    Type: AWS::Serverless::StateMachine
    Properties:
      Name: ai-chef-workflow
      Definition:
        Comment: AI Chef Recipe Generation Workflow
        StartAt: ParallelProcessing
        States:
          ParallelProcessing:
            Type: Parallel
            Branches:
              - StartAt: GenerateRecipe
                States:
                  GenerateRecipe:
                    Type: Task
                    Resource: !GetAtt RecipeFunction.Arn
                    End: true
              - StartAt: GetPriceInfo
                States:
                  GetPriceInfo:
                    Type: Task
                    Resource: !GetAtt PriceFunction.Arn
                    End: true
              - StartAt: CalculateNutrition
                States:
                  CalculateNutrition:
                    Type: Task
                    Resource: !GetAtt NutritionCalculatorFunction.Arn
                    End: true
            Next: CombineResults
          CombineResults:
            Type: Task
            Resource: !GetAtt CombineFunction.Arn
            End: true
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref RecipeFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref PriceFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref NutritionCalculatorFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref CombineFunction

Outputs:
  ApiGatewayUrl:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${AiChefApi}.execute-api.${AWS::Region}.amazonaws.com/prod"
    Export:
      Name: !Sub "${AWS::StackName}-ApiUrl"
  
  SessionsTableName:
    Description: DynamoDB Sessions Table Name
    Value: !Ref SessionsTable
    Export:
      Name: !Sub "${AWS::StackName}-SessionsTable"

  ResultsTableName:
    Description: DynamoDB Results Table Name
    Value: !Ref ResultsTable
    Export:
      Name: !Sub "${AWS::StackName}-ResultsTable"
