AWSTemplateFormatVersion: '2010-09-09'
Description: 'AI Chef DynamoDB Tables Schema'

Resources:
  # CloudWatch Log Group for DynamoDB
  DynamoDBLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: '/aws/dynamodb/ai-chef-tables'
      RetentionInDays: 7

  # CloudWatch Alarm for Sessions Table Errors
  SessionsTableErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: 'AI-Chef-DynamoDB-SessionsTable-Errors'
      AlarmDescription: 'Error monitoring for Sessions DynamoDB Table'
      MetricName: 'ThrottledRequests'
      Namespace: 'AWS/DynamoDB'
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 5
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: TableName
          Value: !Ref AiChefSessionsTable
      TreatMissingData: notBreaching

  AiChefSessionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ai-chef-sessions
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: sessionId
          AttributeType: S
      KeySchema:
        - AttributeName: sessionId
          KeyType: HASH
      TimeToLiveSpecification:
        AttributeName: TTL
        Enabled: true

  AiChefResultsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ai-chef-results
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: resultId
          AttributeType: S
        - AttributeName: sessionId
          AttributeType: S
      KeySchema:
        - AttributeName: resultId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: sessionId-index
          KeySchema:
            - AttributeName: sessionId
              KeyType: HASH
          Projection:
            ProjectionType: ALL

Outputs:
  SessionsTableName:
    Description: 'Sessions table name'
    Value: !Ref AiChefSessionsTable
    Export:
      Name: !Sub '${AWS::StackName}-SessionsTable'

  ResultsTableName:
    Description: 'Results table name'
    Value: !Ref AiChefResultsTable
    Export:
      Name: !Sub '${AWS::StackName}-ResultsTable'
