AWSTemplateFormatVersion: '2010-09-09'
Description: 'AI Chef Recipe Image Generator Lambda Function - Reference Existing'

Parameters:
  ExistingLambdaFunctionName:
    Type: String
    Default: 'recipe-image-generator'
    Description: 'Name of the existing Lambda function to reference'

Outputs:
  RecipeImageGeneratorLambdaArn:
    Description: 'Recipe Image Generator Lambda Function ARN (Referenced)'
    Value: !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${ExistingLambdaFunctionName}'
    Export:
      Name: !Sub '${AWS::StackName}-RecipeImageGeneratorLambdaArn'
      
  ExistingLambdaFunctionName:
    Description: 'Referenced Lambda Function Name'
    Value: !Ref ExistingLambdaFunctionName
    Export:
      Name: !Sub '${AWS::StackName}-ExistingLambdaFunctionName'
