AWSTemplateFormatVersion: '2010-09-09'
Description: 'AI Chef Nutrition Calculator Lambda with OpenSearch integration'

Resources:
  NutritionCalculatorLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: ai-chef-nutrition-calculator
      Runtime: python3.11
      Handler: lambda_function.lambda_handler
      Role: !Sub 'arn:aws:iam::${AWS::AccountId}:role/ai-chef-lambda-role'
      Code:
        ZipFile: |
          import json
          def lambda_handler(event, context):
            return {
              'statusCode': 200,
              'body': json.dumps('Placeholder')
            }
      Description: 'AI Chef nutrition calculator Lambda with OpenSearch integration'
      Timeout: 300
      MemorySize: 512
      Environment:
        Variables:
          DYNAMODB_TABLE: ai-chef-sessions
          RESULTS_TABLE: ai-chef-results
          OPENSEARCH_ENDPOINT: !Sub 'https://search-ai-chef-opensearch-${AWS::AccountId}.us-east-1.es.amazonaws.com'

  NutritionCalculatorLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${NutritionCalculatorLambda}'
      RetentionInDays: 7

Outputs:
  NutritionCalculatorLambdaArn:
    Description: 'Nutrition Calculator Lambda ARN'
    Value: !GetAtt NutritionCalculatorLambda.Arn
    Export:
      Name: !Sub '${AWS::StackName}-NutritionCalculatorLambdaArn'
