AWSTemplateFormatVersion: '2010-09-09'
Description: 'AI Chef Price Lambda Function - Secrets Manager Version'

Resources:
  # Naver API Secrets
  NaverApiSecrets:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: 'ai-chef/naver-api'
      Description: 'Naver Shopping API credentials for AI Chef'
      SecretString: !Sub |
        {
          "client_id": "5A_tDnltTaEiCEsXbHH7",
          "client_secret": "ygjYjr9oqc"
        }

  # Lambda Execution Role
  PriceLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: DynamoDBAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:Query
                  - dynamodb:Scan
                Resource: 
                  - !Sub 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/ai-chef-sessions'
        - PolicyName: SecretsManagerAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: !Ref NaverApiSecrets

  # Price Lambda Function
  PriceLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: 'ai-chef-price'
      Runtime: python3.11
      Handler: lambda_function.lambda_handler
      Role: !GetAtt PriceLambdaRole.Arn
      Timeout: 30
      MemorySize: 256
      Environment:
        Variables:
          NAVER_API_SECRET_NAME: !Ref NaverApiSecrets
          SESSIONS_TABLE_NAME: 'ai-chef-sessions'
      Code:
        ZipFile: |
          # Placeholder - will be replaced by deployment script with actual ZIP file
          import json
          def lambda_handler(event, context):
              return {'statusCode': 200, 'body': {'message': 'Placeholder function'}}

Outputs:
  PriceLambdaArn:
    Description: 'Price Lambda Function ARN'
    Value: !GetAtt PriceLambda.Arn
    Export:
      Name: !Sub '${AWS::StackName}-PriceLambdaArn'
  
  NaverApiSecretsArn:
    Description: 'Naver API Secrets ARN'
    Value: !Ref NaverApiSecrets
    Export:
      Name: !Sub '${AWS::StackName}-NaverApiSecretsArn'
