AWSTemplateFormatVersion: '2010-09-09'
Description: 'AI Chef Step Functions with Parallel Processing'

Resources:
  # Step Functions Execution Role
  StepFunctionsRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: states.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaInvokePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource:
                  - 'arn:aws:lambda:*:*:function:ai-chef-recipe'
                  - 'arn:aws:lambda:*:*:function:ai-chef-nutrition-calculator'
                  - 'arn:aws:lambda:*:*:function:ai-chef-price'
                  - 'arn:aws:lambda:*:*:function:ai-chef-recipe-image-generator'
                  - 'arn:aws:lambda:*:*:function:ai-chef-combine'

  # Step Functions State Machine
  RecipeWorkflowStateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineName: 'ai-chef-workflow'
      RoleArn: !GetAtt StepFunctionsRole.Arn
      DefinitionString: |
        {
          "Comment": "AI Chef Workflow - Recipe RAG then Parallel Processing",
          "StartAt": "CreateRecipeWithRAG",
          "States": {
            "CreateRecipeWithRAG": {
              "Type": "Task",
              "Resource": "arn:aws:states:::lambda:invoke",
              "Parameters": {
                "FunctionName": "ai-chef-recipe",
                "Payload.$": "$"
              },
              "ResultSelector": {
                "recipe.$": "$.Payload.body"
              },
              "ResultPath": "$.recipeResult",
              "Next": "ParallelProcessing"
            },
            "ParallelProcessing": {
              "Type": "Parallel",
              "Branches": [
                {
                  "StartAt": "NutritionCalculator",
                  "States": {
                    "NutritionCalculator": {
                      "Type": "Task",
                      "Resource": "arn:aws:states:::lambda:invoke",
                      "Parameters": {
                        "FunctionName": "ai-chef-nutrition-calculator",
                        "Payload": {
                          "sessionId.$": "$.sessionId",
                          "recipe.$": "$.recipeResult.recipe"
                        }
                      },
                      "End": true
                    }
                  }
                },
                {
                  "StartAt": "FetchPrices",
                  "States": {
                    "FetchPrices": {
                      "Type": "Task",
                      "Resource": "arn:aws:states:::lambda:invoke",
                      "Parameters": {
                        "FunctionName": "ai-chef-price",
                        "Payload": {
                          "sessionId.$": "$.sessionId",
                          "profile.$": "$.profile",
                          "ingredients.$": "$.recipeResult.recipe.ingredients"
                        }
                      },
                      "End": true
                    }
                  }
                },
                {
                  "StartAt": "GenerateImage",
                  "States": {
                    "GenerateImage": {
                      "Type": "Task",
                      "Resource": "arn:aws:states:::lambda:invoke",
                      "Parameters": {
                        "FunctionName": "ai-chef-recipe-image-generator",
                        "Payload": {
                          "sessionId.$": "$.sessionId",
                          "recipe.$": "$.recipeResult.recipe"
                        }
                      },
                      "End": true
                    }
                  }
                }
              ],
              "ResultPath": "$.parallelResults",
              "Next": "CombineResults"
            },
            "CombineResults": {
              "Type": "Task",
              "Resource": "arn:aws:states:::lambda:invoke",
              "Parameters": {
                "FunctionName": "ai-chef-combine",
                "Payload": {
                  "sessionId.$": "$.sessionId",
                  "profile.$": "$.profile",
                  "recipeResult.$": "$.recipeResult.recipe",
                  "nutritionResult.$": "$.parallelResults[0].Payload.body",
                  "pricingResult.$": "$.parallelResults[1].Payload.body",
                  "imageResult.$": "$.parallelResults[2].Payload.body"
                }
              },
              "End": true
            }
          }
        }

Outputs:
  StateMachineArn:
    Description: 'Step Functions State Machine ARN'
    Value: !Ref RecipeWorkflowStateMachine
    Export:
      Name: !Sub '${AWS::StackName}-StateMachineArn'
