AWSTemplateFormatVersion: '2010-09-09'
Description: 'AI Chef Step Functions with Parallel Processing'

Resources:
  # Step Functions Execution Role
  StepFunctionsRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: states.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaInvokePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource: '*'

  # Step Functions State Machine
  RecipeWorkflowStateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineName: 'ai-chef-workflow'
      RoleArn: !GetAtt StepFunctionsRole.Arn
      DefinitionString: |
        {
          "Comment": "AI Chef Workflow with Parallel Processing",
          "StartAt": "CreateRecipeWithRAG",
          "States": {
            "CreateRecipeWithRAG": {
              "Type": "Task",
              "Resource": "arn:aws:states:::lambda:invoke",
              "Parameters": {
                "FunctionName": "create-recipe-with-rag",
                "Payload.$": "$"
              },
              "ResultSelector": {
                "recipe.$": "$.Payload.body"
              },
              "ResultPath": "$.recipeResult",
              "Next": "ParallelProcessing"
            },
            "ParallelProcessing": {
              "Type": "Parallel",
              "Branches": [
                {
                  "StartAt": "FetchPrices",
                  "States": {
                    "FetchPrices": {
                      "Type": "Task",
                      "Resource": "arn:aws:states:::lambda:invoke",
                      "Parameters": {
                        "FunctionName": "ai-chef-price",
                        "Payload": {
                          "sessionId.$": "$.sessionId",
                          "profile.$": "$.profile",
                          "recipeResult.$": "$.recipeResult"
                        }
                      },
                      "ResultSelector": {
                        "pricing.$": "$.Payload.body"
                      },
                      "End": true
                    }
                  }
                },
                {
                  "StartAt": "CalculateNutrition",
                  "States": {
                    "CalculateNutrition": {
                      "Type": "Task",
                      "Resource": "arn:aws:states:::lambda:invoke",
                      "Parameters": {
                        "FunctionName": "ai-chef-nutrition-calculator",
                        "Payload": {
                          "sessionId.$": "$.sessionId",
                          "profile.$": "$.profile",
                          "recipeData.$": "$.recipeResult.recipe"
                        }
                      },
                      "ResultSelector": {
                        "nutrition.$": "$.Payload"
                      },
                      "End": true
                    }
                  }
                },
                {
                  "StartAt": "GenerateRecipeImage",
                  "States": {
                    "GenerateRecipeImage": {
                      "Type": "Task",
                      "Resource": "arn:aws:states:::lambda:invoke",
                      "Parameters": {
                        "FunctionName": "recipe-image-generator",
                        "Payload": {
                          "sessionId.$": "$.sessionId",
                          "recipe.$": "$.recipeResult.recipe"
                        }
                      },
                      "ResultSelector": {
                        "image.$": "$.Payload.body"
                      },
                      "End": true
                    }
                  }
                }
              ],
              "ResultPath": "$.parallelResults",
              "Next": "CombineResults"
            },
            "CombineResults": {
              "Type": "Task",
              "Resource": "arn:aws:states:::lambda:invoke",
              "Parameters": {
                "FunctionName": "ai-chef-combine",
                "Payload": {
                  "sessionId.$": "$.sessionId",
                  "profile.$": "$.profile",
                  "recipeResult.$": "$.recipeResult.recipe",
                  "pricingResult.$": "$.parallelResults[0].pricing",
                  "nutritionResult.$": "$.parallelResults[1].nutrition",
                  "imageResult.$": "$.parallelResults[2].image"
                }
              },
              "End": true
            }
          }
        }

Outputs:
  StateMachineArn:
    Description: 'Step Functions State Machine ARN'
    Value: !Ref RecipeWorkflowStateMachine
    Export:
      Name: !Sub '${AWS::StackName}-StateMachineArn'
