name: Deploy API Gateway Only

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Type "deploy" to confirm'
        required: true
        default: ''

jobs:
  deploy-api-gateway:
    runs-on: ubuntu-latest
    if: github.event.inputs.confirm == 'deploy'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    
    - name: Deploy API Gateway Only
      run: |
        cd backend/infrastructure
        chmod +x deploy-api-gateway.sh
        ./deploy-api-gateway.sh
    
    - name: Discord Success Notification
      if: success()
      run: |
        curl -H "Content-Type: application/json" \
        -d '{
          "embeds": [{
            "title": "✅ API Gateway Deployed",
            "description": "ai-chef-api Gateway deployed successfully",
            "color": 3066993,
            "fields": [
              {"name": "Resource", "value": "API Gateway Only", "inline": true},
              {"name": "Commit", "value": "${{ github.sha }}", "inline": true}
            ]
          }]
        }' \
        https://discord.com/api/webhooks/1399402822105038999/2qQDazifNKeW_c8MhHqcrw6Li5yDQtBL7f2JIBQ_b4qVT3Vxh7TfpMV3kBFnDYAFL3-h
    
    - name: Discord Failure Notification
      if: failure()
      run: |
        curl -H "Content-Type: application/json" \
        -d '{
          "embeds": [{
            "title": "❌ API Gateway Deployment Failed",
            "description": "ai-chef-api Gateway deployment failed",
            "color": 15158332,
            "fields": [
              {"name": "Resource", "value": "API Gateway Only", "inline": true},
              {"name": "Commit", "value": "${{ github.sha }}", "inline": true}
            ]
          }]
        }' \
        https://discord.com/api/webhooks/1399402822105038999/2qQDazifNKeW_c8MhHqcrw6Li5yDQtBL7f2JIBQ_b4qVT3Vxh7TfpMV3kBFnDYAFL3-h
