name: Deploy Session Create Lambda Only

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Type "deploy" to confirm'
        required: true
        default: ''

jobs:
  deploy-session-create:
    runs-on: ubuntu-latest
    if: github.event.inputs.confirm == 'deploy'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    
    - name: Deploy Session Create Lambda Only
      run: |
        cd backend/infrastructure
        aws cloudformation deploy \
          --template-file session-create-lambda.yaml \
          --stack-name ai-chef-session-create-lambda \
          --capabilities CAPABILITY_IAM \
          --region us-east-1
    
    - name: Discord Success Notification
      if: success()
      run: |
        curl -H "Content-Type: application/json" \
        -d '{
          "embeds": [{
            "title": "✅ Session Create Lambda Deployed",
            "description": "ai-chef-session-create function deployed successfully",
            "color": 3066993,
            "fields": [
              {"name": "Function", "value": "ai-chef-session-create", "inline": true},
              {"name": "Commit", "value": "${{ github.sha }}", "inline": true}
            ]
          }]
        }' \
        https://discord.com/api/webhooks/1399402822105038999/2qQDazifNKeW_c8MhHqcrw6Li5yDQtBL7f2JIBQ_b4qVT3Vxh7TfpMV3kBFnDYAFL3-h
    
    - name: Discord Failure Notification
      if: failure()
      run: |
        curl -H "Content-Type: application/json" \
        -d '{
          "embeds": [{
            "title": "❌ Session Create Lambda Failed",
            "description": "ai-chef-session-create deployment failed",
            "color": 15158332,
            "fields": [
              {"name": "Function", "value": "ai-chef-session-create", "inline": true},
              {"name": "Commit", "value": "${{ github.sha }}", "inline": true}
            ]
          }]
        }' \
        https://discord.com/api/webhooks/1399402822105038999/2qQDazifNKeW_c8MhHqcrw6Li5yDQtBL7f2JIBQ_b4qVT3Vxh7TfpMV3kBFnDYAFL3-h
